name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    name: npm publish
    runs-on: ubuntu-slim
    permissions:
      id-token: write # Required for OIDC
      contents: write # softprops/action-gh-release
      attestations: write # actions/attest-build-provenance
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      - name: Extract Version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            version="${{ inputs.version }}"
          else
            version=$(node -p "require('./package.json').version")
          fi
          echo "VERSION=$version" >> "$GITHUB_ENV"
      - run: pnpm publish --no-git-checks
      - name: Rename CLI artifact
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          artifact="dist/${repo}-v${{ env.VERSION }}.js"
          mv dist/cli.js "$artifact"
          echo "CLI_ARTIFACT=$artifact" >> "$GITHUB_ENV"
      - uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: ${{ env.CLI_ARTIFACT }}
      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: ${{ env.CLI_ARTIFACT }}
          tag_name: v${{ env.VERSION }}
