name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [latest, lts/*, lts/-1]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test

  automerge:
    if: github.triggering_actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
